### ISSUE TITLE
Build Fail

### ISSUE THREAD

**Issue by R-ad** [p-web-git/hostapd#3]
First of all thank you for your patch!

I have failed build with 2.11 patch.
Patch correctly applied to hostapd-2025.06.27

Peace of build log with fail:
```
../src/ap/hostapd.c: In function 'hostapd_scan_results_updated':
../src/ap/hostapd.c:2099:13: error: 'initiator' undeclared (first use in this function); did you mean 'inet_aton'?
 2099 |         if (initiator == REGDOM_SET_BY_DRIVER) {
      |             ^~~~~~~~~
      |             inet_aton

```

Problematic Part of hostapd.c after patch:
```
}


void hostapd_channel_list_updated(struct hostapd_iface *iface, int initiator)
{}


void hostapd_scan_results_updated(struct hostapd_iface *iface)
{
	if (initiator == REGDOM_SET_BY_DRIVER) {
		hostapd_for_each_interface(iface->interfaces,
					   hostapd_no_ir_channel_list_updated,
					   NULL);
		return;
	}

	if (!iface->wait_channel_update)
		return;

	wpa_printf(MSG_DEBUG, "Scan results updated - continue setup");
	eloop_cancel_timeout(channel_list_update_timeout, iface, NULL);
	setup_interface2(iface);
}
```

Part of hostapd.c before patch:
```
}


void hostapd_channel_list_updated(struct hostapd_iface *iface, int initiator)
{
	if (initiator == REGDOM_SET_BY_DRIVER) {
		hostapd_for_each_interface(iface->interfaces,
					   hostapd_no_ir_channel_list_updated,
					   NULL);
		return;
	}

	if (!iface->wait_channel_update)
		return;

	wpa_printf(MSG_DEBUG, "Scan results updated - continue setup");
	eloop_cancel_timeout(channel_list_update_timeout, iface, NULL);
	setup_interface2(iface);
}
```

All other part of patch work correct.
Problem only in part:
```
void hostapd_scan_results_updated(struct hostapd_iface *iface)
{
	if (initiator == REGDOM_SET_BY_DRIVER) {
		hostapd_for_each_interface(iface->interfaces,
					   hostapd_no_ir_channel_list_updated,
					   NULL);
		return;
	}
```

Please, help to solve this issue)

**Comment by PedroFirmware** [comment]
Hey R-ad

At the moment I  can't tests the hostapd 2.11 on my computer, but I solved the build error that you mentioned. Would you be able to test the patch from the test branch[ v2.11-patch-changes](https://github.com/p-web-git/hostapd/blob/v2.11-patch-changes/For_intel_Wi-Fi_cards_v2_11.patch) and report if it worked?
